#!/bin/bash

INTERVAL=$1

if [[ q$INTERVAL == 'q' ]]
then
	INTERVAL=30000
fi

TIMESTAMP=`date +%m%Y%d_%H%M%S`

ps -ef | grep db_slv | grep -v grep
if [[ $? -ne 0 ]]
then
	echo "Executing stopsystem"
	/home/sj_i680_capitol/ramp_metering/system/stopsystem
	echo "Starting restart_system with interval $INTERVAL ms"
	echo "Starting urmsgo_all $INTERVAL"
	/home/sj_i680_capitol/ramp_metering/system/urmsgo_all $INTERVAL
	/home/sj_i680_capitol/arterial/system/data_file_2_database.sh
	cd /home/sj_i680_capitol/ramp_metering/src
	mkdir Out_Data_$TIMESTAMP
	rm Out_Data
	ln -s Out_Data_$TIMESTAMP Out_Data
	echo "Starting opt_crm $INTERVAL"
	./lnx/opt_crm -i $INTERVAL -d >/linux2/big/data/SANJOSE_ACRM/opt_crm_$TIMESTAMP.txt &
	exit 1
fi

RESTART_LOGFILE=/linux2/big/data/SANJOSE_ACRM/restart_$TIMESTAMP

for x in `cat /home/sj_i680_capitol/ramp_metering/system/urmsgo_all | grep urmsgo | grep system | grep -v '^#' | awk '{print $2}'`
do 
	CONTROLLER_IP=$x
	URMS_STATUS_DBNUM=`cat /home/sj_i680_capitol/ramp_metering/system/urmsgo_all | grep $x | grep -v '^#' | awk '{print $3}'`
	PORT=`cat /home/sj_i680_capitol/ramp_metering/system/urmsgo_all | grep $x | grep -v '^#' | awk '{print $4}'`
	NUM_CONTROLLERS=1

	URMS_STATUS_DBNUM2=`echo $URMS_STATUS_DBNUM | awk '{print $2}'`
echo CONTROLLER_IP $CONTROLLER_IP PORT $PORT DBNUM $URMS_STATUS_DBNUM >>$RESTART_LOGFILE

	if [[ q$URMS_STATUS_DBNUM2 != 'q' ]] # Some modems had 2 controllers on their LANs, with different ports assigned
	then
		PORT2=`echo $PORT | awk '{print $2}'`
		PORT=`echo $PORT | awk '{print $1}'`
		URMS_STATUS_DBNUM=`echo $URMS_STATUS_DBNUM | awk '{print $1}'`
		NUM_CONTROLLERS=2
	fi

	for((INDEX=$NUM_CONTROLLERS ; $INDEX>0 ; INDEX=$(($INDEX-1)) ))
#	for((INDEX=$NUM_CONTROLLERS ; $INDEX>0 ; INDEX-- ))
	do
echo PORT11 $PORT INDEX $INDEX >>$RESTART_LOGFILE
		#Check wrfiles running first
		ps -ef | grep wrfiles_rm | grep $x | grep -v grep
		if [[ $? -ne 0 ]]
		then 
       		 	echo "Starting wrfiles_rm, $CONTROLLER_IP $URMS_STATUS_DBNUM $PORT $TIMESTAMP" >>$RESTART_LOGFILE
			/home/sj_i680_capitol/ramp_metering/src/lnx/wrfiles_rm -d /linux2/big/data/SANJOSE_ACRM -i 30000 -m 30 -s $URMS_STATUS_DBNUM -c $CONTROLLER_IP"."$PORT"."$TIMESTAMP 1>>/linux2/big/data/SANJOSE_ACRM/"wrfiles_ac_rm_"$CONTROLLER_IP"_"$PORT"."$TIMESTAMP".err" 2>&1 &
			sleep 5
		fi

echo PORT2 $PORT
		#Check good data in log file, and kill urms if it's all the same (except for the timestamp)
# 28 was for sr99		for FILE in `ls -tr /linux2/big/data/SANJOSE_ACRM/*.dat |tail -28 | grep $CONTROLLER_IP | grep $PORT`
		for FILE in `ls -tr "/linux2/big/data/SANJOSE_ACRM/a_"$CONTROLLER_IP.$PORT*"dat" |tail -50 | grep $CONTROLLER_IP | grep $PORT | tail -1`
		do
			NOW=`date +%s`
			OPEN=`stat $FILE -c %X`
echo NOW $NOW OPEN $OPEN FILE $FILE
			DIFF=$(($NOW - $OPEN))
			if [[ $DIFF -gt 90 ]] #In 90 seconds, there should be 3 raw data calculations, as well as numerous updates of the "seconds" column
			then
				NUMDIFF=`cat $FILE | cut -d ' ' -f 2- | uniq -c| wc | awk '{print $1}'`
				if [[ $NUMDIFF -lt 3 ]]
				then 
					PID=`ps -elf | grep  urms | grep $CONTROLLER_IP | grep $PORT | awk '{print $4}'`
					if [[ q$PID == 'q' ]]
					then
						echo $CONTROLLER_IP $PORT no good >>$RESTART_LOGFILE
# telnet only works for sr99			{ echo "super user" ; sleep 2; echo "break"; sleep 1; } | telnet $CONTROLLER_IP 231
						sudo kill $PID
					fi
				fi
			fi
		done

		#Now that urms is dead, check whether the TCP connection has timed out (this will take a couple of minutes, so
		#this check will succeed the next time the script is run).
echo PORT3 $PORT
		netstat -an | grep $CONTROLLER_IP | grep $PORT
		if [[ $? -ne 0 ]] 
		then 
			echo $CONTROLLER_IP urms process not running. Attempting restart.... >>$RESTART_LOGFILE

			cat /home/sj_i680_capitol/ramp_metering/system/urmsgo_all | grep $CONTROLLER_IP | grep control | grep -v '^#'
			if [[ $? == 0 ]]
			then			
				/home/atsc/urms/lnx/urms -r $CONTROLLER_IP -i 30000 -d $URMS_STATUS_DBNUM -p $PORT >/linux2/big/data/SANJOSE_ACRM/"urms_"$CONTROLLER_IP"."$PORT"."$TIMESTAMP".err" 2>&1 &
				CONTROL=under_control
			else
				/home/atsc/urms/lnx/urms -n -r $CONTROLLER_IP -i 30000 -d $URMS_STATUS_DBNUM -p $PORT >/linux2/big/data/SANJOSE_ACRM/"urms_"$CONTROLLER_IP"."$PORT"."$TIMESTAMP".err" 2>&1 &
				CONTROL=no_control
			fi
			echo CONTROLLER_IP $CONTROLLER_IP URMS_STATUS_DBNUM $URMS_STATUS_DBNUM PORT $PORT $CONTROL >>$RESTART_LOGFILE
			sleep 5
		fi
		PORT=$PORT2
		URMS_STATUS_DBNUM=$URMS_STATUS_DBNUM2
	done
done

ps -ef | grep opt_crm | grep -v grep | grep -v vi
if [[ $? -ne 0 ]]
then
	cd /home/sj_i680_capitol/ramp_metering/src
	mkdir Out_Data_$TIMESTAMP
	rm Out_Data
	ln -s Out_Data_$TIMESTAMP Out_Data
	./lnx/opt_crm -i $INTERVAL -d >/linux2/big/data/SANJOSE_ACRM/opt_crm_$TIMESTAMP.txt &
#	./lnx/opt_crm -i $INTERVAL >/dev/null &
fi
