#!/bin/bash

INTERVAL=5000

echo "Executing stopusystem"
/home/sj_i680_capitol/ramp_metering/system/stopsystem
sleep 1

echo "Starting db_slv"
/home/path/db/lnx/db_slv &
sleep 1

echo "Starting clt_vars"
/home/sj_i680_capitol/ramp_metering/src/lnx/clt_vars &
sleep 1

TIMESTAMP=`date +%y%m%d_%H%M%S`

echo "Starting urmsgo with interval $INTERVAL control $CONTROL"

/home/sj_i680_capitol/ramp_metering/system/urmsgo 10.192.131.125 3800 1000 $TIMESTAMP $INTERVAL control
sleep 1
#/home/sj_i680_capitol/ramp_metering/system/urmsgo 10.29.248.81	3800	1000	$TIMESTAMP $INTERVAL control
#sleep 1

cd /home/sj_i680_capitol/ramp_metering/src
mkdir Out_Data_$TIMESTAMP
ln -s Out_Data_$TIMESTAMP Out_Data
./lnx/opt_crm -i $INTERVAL >/linux2/big/data/SANJOSE_ACRM/opt_crm_$TIMESTAMP.txt &
sleep 1
#./lnx/db_set_pattern >/linux2/big/data/SANJOSE_ACRM/db_set_pattern_$TIMESTAMP.txt &
./lnx/db_set_pattern
